name: Publish PDF

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install LaTeX tools
        run: make setup
      
      - name: Compile LaTeX document
        run: make build
      
      - name: Upload PDF document
        uses: actions/upload-artifact@v2
        with:
          name: rad
          path: rad.pdf
